version: '3'

services:
  mysqlsrv:
    image: "mysql:5.7"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  appsrv:
    image: "monitauro/devbase-base:ubuntu-16.04"
    container_name: app
    ports:
      - "80:80"
      - "9001:9001"
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/sites-enabled/default:ro
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge